import { PGlite } from '@electric-sql/pglite'
import { sql } from 'drizzle-orm'
import { drizzle } from 'drizzle-orm/pglite'
import { migrate } from 'drizzle-orm/pglite/migrator'
import { beforeAll, describe, expect, it } from 'vitest'
import { createBackup, restoreBackup } from '@/core/ops/backup'
import { getPendingMigrations } from '@/core/ops/upgrade'
import { applyPgliteStatementTimeout } from '@/db/backend'
import * as schema from '@/db/schema'

type DB = ReturnType<typeof drizzle<typeof schema>>
let db: DB

beforeAll(async () => {
  const client = new PGlite() // in-memory
  db = drizzle(client, { schema })
  await migrate(db, { migrationsFolder: './drizzle' })
})

describe('pglite backend contract', () => {
  it('applies all repo migrations and creates core tables', async () => {
    const res = await db.execute(
      sql`SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name IN ('users','settings','artists')`,
    )
    expect(res.rows.length).toBe(3)
  })

  it('creates nullable text unreconciled reason columns', async () => {
    const res = await db.execute(sql`
      SELECT table_name, column_name, data_type, is_nullable
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name IN ('library_albums', 'library_artists')
        AND column_name = 'unreconciled_reason'
      ORDER BY table_name
    `)

    expect(res.rows).toEqual([
      {
        table_name: 'library_albums',
        column_name: 'unreconciled_reason',
        data_type: 'text',
        is_nullable: 'YES',
      },
      {
        table_name: 'library_artists',
        column_name: 'unreconciled_reason',
        data_type: 'text',
        is_nullable: 'YES',
      },
    ])
  })

  it('db.execute returns the {rows} shape upgrade.ts/health depend on', async () => {
    const res = await db.execute(sql`SELECT 1 AS x`)
    expect(Array.isArray(res.rows)).toBe(true)
    expect((res.rows[0] as { x: number }).x).toBe(1)
  })

  it('getPendingMigrations works against pglite introspection', async () => {
    const status = await getPendingMigrations(db as never)
    expect(status.pendingCount).toBe(0)
    expect(status.targetVersion).not.toBeNull()
  })

  it('caps queries with a 30s statement_timeout, matching the Postgres path', async () => {
    const client = new PGlite() // in-memory
    await applyPgliteStatementTimeout(client)
    const res = await client.query<{ statement_timeout: string }>('SHOW statement_timeout')
    expect(res.rows[0]?.statement_timeout).toBe('30s')
  }, 20_000)

  it('round-trips a backup on pglite', async () => {
    await db.execute(sql`INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING`)
    const backup = await createBackup(db as never, { includeCaches: true })
    const result = await restoreBackup(db as never, backup, { force: true })
    expect(result.tablesRestored.settings).toBeGreaterThanOrEqual(1)
    expect(result.warnings).toEqual([])
  })

  // Migration 0046 converted every legacy `serial` primary key to
  // `GENERATED BY DEFAULT AS IDENTITY`. BY DEFAULT (not ALWAYS) is load-bearing:
  // backup restore inserts explicit ids, which ALWAYS would reject.
  it('exposes all id primary keys as BY DEFAULT identity columns', async () => {
    const res = await db.execute<{
      is_identity: string
      identity_generation: string | null
    }>(sql`
      SELECT is_identity, identity_generation
      FROM information_schema.columns
      WHERE table_schema = 'public' AND column_name = 'id'
    `)
    expect(res.rows.length).toBe(24)
    expect(res.rows.every((r) => r.is_identity === 'YES')).toBe(true)
    expect(res.rows.every((r) => r.identity_generation === 'BY DEFAULT')).toBe(true)
  })

  it('auto-assigns identity ids yet still accepts explicit ids (BY DEFAULT)', async () => {
    const [auto] = await db
      .insert(schema.users)
      .values({ username: 'identity-auto', passwordHash: 'x' })
      .returning()
    expect(typeof auto?.id).toBe('number')

    const [explicit] = await db
      .insert(schema.users)
      .values({ id: 987654, username: 'identity-explicit', passwordHash: 'x' })
      .returning()
    expect(explicit?.id).toBe(987654)
  })

  // Much app code calls .toISOString()/.getTime() on selected timestamp columns.
  // Confirm drizzle's timestamp({withTimezone}) maps to a JS Date under PGlite,
  // selected through the QUERY BUILDER (not raw execute), for a representative table.
  it('returns timestamptz columns as Date via the query builder', async () => {
    const [row] = await db
      .insert(schema.users)
      .values({ username: 'tz-probe', passwordHash: 'x' })
      .returning()
    expect(row).toBeDefined()
    expect(row?.createdAt).toBeInstanceOf(Date)
  })
})
