-- Convert legacy `serial` primary keys to `GENERATED BY DEFAULT AS IDENTITY`.
--
-- Hand-authored: drizzle-kit's autogen emits `SET DATA TYPE integer` + `ADD
-- GENERATED ... AS IDENTITY` but never drops the serial's `nextval` default, so
-- the ADD fails on real tables, and its `START WITH 1` would collide with
-- existing rows. This dynamic block converts exactly the serial `id` columns,
-- drops the orphaned `<table>_id_seq` so identity can reclaim the same name
-- (keeping the drizzle snapshot accurate), and preserves the live sequence
-- value as MAX(id)+1. Idempotent: identity columns report a NULL default, so a
-- re-run matches nothing. Works on both PostgreSQL and the embedded PGlite
-- backend.
DO $$
DECLARE
  r record;
  old_seq text;
BEGIN
  FOR r IN
    SELECT table_name, column_name
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND column_name = 'id'
      AND column_default LIKE 'nextval(%'
  LOOP
    old_seq := pg_get_serial_sequence(format('public.%I', r.table_name), r.column_name);
    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I DROP DEFAULT', r.table_name, r.column_name);
    IF old_seq IS NOT NULL THEN
      EXECUTE format('DROP SEQUENCE IF EXISTS %s', old_seq);
    END IF;
    EXECUTE format('ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY', r.table_name, r.column_name);
    EXECUTE format(
      'SELECT setval(pg_get_serial_sequence(%L, %L), GREATEST(COALESCE((SELECT MAX(%I) FROM %I), 0) + 1, 1), false)',
      format('public.%I', r.table_name), r.column_name, r.column_name, r.table_name
    );
  END LOOP;
END $$;
