CREATE TABLE IF NOT EXISTS "oauth_pending_auths" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "oauth_pending_auths_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL CONSTRAINT "oauth_pending_auths_user_id_users_id_fk" REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action,
	"provider" text NOT NULL,
	"state_hash" text NOT NULL,
	"binding_hash" text NOT NULL,
	"payload" text,
	"scopes" text,
	"client_id" text,
	"client_secret" text,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "oauth_pending_auths_provider_state" UNIQUE("provider","state_hash")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "oauth_pending_auths_user_provider_idx" ON "oauth_pending_auths" USING btree ("user_id","provider");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "oauth_pending_auths_expires_idx" ON "oauth_pending_auths" USING btree ("expires_at");--> statement-breakpoint
-- In-flight authorizations used to live in `oauth_tokens` as a `pending:` marker
-- that overwrote the real token row. Those markers are never written again and a
-- surviving one would read as a connected account, so drop them.
DELETE FROM "oauth_tokens" WHERE "access_token" LIKE 'pending:%';
